name: Deploy Docker Image

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on: [push]
    
env:
  IMAGE_NAME: linux_tweet_app

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GCR
        env:
          IMAGE_NAME: linux_tweet_app
          PROJECT_ID: service-project-ardhan-1
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
          
      - name: Build Docker Image
        env:
          IMAGE_NAME: linux_tweet_app
          PROJECT_ID: service-project-ardhan-1
        run: docker build -t $IMAGE_NAME:latest .
        
      - name: Configure Docker Client
        run:  |-
          gcloud auth configure-docker --quiet
        
      - name: Push Docker Image to Container Registry GCR
        env: 
          GIT_TAG: v0.1.1
          IMAGE_NAME: linux_tweet_app
          PROJECT_ID: service-project-ardhan-1
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

      - name: Extract metadata (tags, labels) for Docker
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: linux_tweet_app
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
